"""
IDCTS ZIP 패키지 생성 모듈
"""

import zipfile
from pathlib import Path
from datetime import datetime


def create_evidence_package(
    case_id: str,
    summary_report: str,
    legal_statement: str,
    dmca_notice: str,
    output_dir: Path,
    har_analysis: str = None,
) -> Path:
    """
    증거 패키지 ZIP 생성
    """
    
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    zip_filename = f"CASE_{timestamp}.zip"
    zip_path = output_dir / zip_filename
    
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zf:
        # 1. 분석 보고서
        zf.writestr("summary_report.txt", summary_report)
        
        # 2. 법적 진술서
        zf.writestr("legal_statement.txt", legal_statement)
        
        # 3. DMCA Notice
        zf.writestr("dmca_or_abuse.txt", dmca_notice)
        
        # 4. HAR 분석 결과 (있는 경우)
        if har_analysis:
            zf.writestr("har_analysis.txt", har_analysis)
        
        # 5. README
        readme = f"""================================================================================
IDCTS 증거 패키지
================================================================================

Case ID: {case_id}
생성 일시: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

================================================================================
포함 파일
================================================================================

1. summary_report.txt
   - 분석 요약 보고서
   - 기관 내부 검토 및 보고용

2. legal_statement.txt
   - 법적 진술서 양식
   - 피해자 작성 후 제출용

3. dmca_or_abuse.txt
   - DMCA/Abuse 신고 양식
   - 해외 CDN/호스팅 업체 제출용

4. har_analysis.txt (선택)
   - HAR 파일 분석 결과
   - 네트워크 증거 상세

================================================================================
사용 방법
================================================================================

1. summary_report.txt로 상황 파악
2. legal_statement.txt 작성 및 서명
3. dmca_or_abuse.txt에 정보 기입 후 발송
4. 삭제 여부 모니터링

================================================================================
주의사항
================================================================================

※ 본 패키지는 분석 도구의 자동 생성물입니다.
※ 법적 효력을 위해서는 전문가 검토를 권장합니다.
※ 본 시스템은 콘텐츠를 직접 삭제하지 않습니다.

================================================================================
Generated by IDCTS Core v2.1
AboutUs Digital Undertaker
https://aboutusforyou.com
================================================================================
"""
        zf.writestr("README.txt", readme)
    
    return zip_path
